<?php

/**
 * Implements hook_config_schema_info_alter().
 */
function commerce_examples_config_schema_info_alter(&$definitions) {
  if (isset($definitions['migrate_plus.source.*'])) {
    $definitions['migrate_plus.source.*']['mapping'] = [
      'keys' => [
        'type' => 'sequence',
        'label' => 'Extra keys',
        'sequence' => [
          'type' => 'string',
          'label' => 'Key',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_theme().
 */
function commerce_examples_theme($existing, $type, $theme, $path) {
  return [
    'commerce_product__full' => [
      'render element' => 'elements',
      'base hook' => 'commerce_product',
    ],
  ];
}
